Iter20
Vidkin/metrics pull request #21
Opened 2024-10-06 20:39 UTC by Vidkin

2024-10-10 02:24 UTC, capsulated requested changes
godoc к staticlint надо добавить, с описанием запуска анализаторов. И по тестам, вроде без докера тесты можно было запустить? Или нет? В любом случае в readme.md или godoc добавить инструкцию по минимальному запуску и docker-compose.yaml как я понимаю

Не могу ни тесты, ни анализаторы чекнуть ((

2024-10-10 12:52 UTC, Vidkin commented
@capsulated 

1) добавил godoc для пакета staticlint, где привёл примеры запуска

2) такое же описание добавил в readme.md

3) добавил в readme.md описание запуска тестов, все тесты запускаются без докера, кроме тех, что предназначены для тестирования хранилища postgresql. Для этих тестов требуется, чтобы на локальном компе был поднят postgresql на порту 5432, с логином\паролем postgres. Добавил в проект docker-compose.yaml для возможности поднять нужный контейнер.

2024-10-10 12:53 UTC, Vidkin commented
@capsulated также в profiles/coverage лежит актуальный coverage.html, в котором можно посмотреть процент покрытия

2024-10-13 23:04 UTC, capsulated commented
> @capsulated также в profiles/coverage лежит актуальный coverage.html, в котором можно посмотреть процент покрытия

Да, это я заметил - это плюс)) Но  profiles/coverage есть вероятность забыть обновить после изменеий)

2024-10-14 14:18 UTC, capsulated approved these changes

2024-10-14 14:23 UTC, merged